### ISSUE TITLE
Output ASN1UnimplementedTag instead of throwing exceptions for unimplemented tags

### ISSUE THREAD

**Issue by jonaskello** [wstrange/asn1lib#14]
I was trying to pase a X509 cert to get the public key. Some tags were unsupported so I got an exception from asn1parser.dart _doPrimitive(): throw new ASN1Exception("Parser for tag ${tag} not implemented yet"). (They are fixed in my pull request for #12).

In my case I did not need any info from the unimplemented tags but I could not get any info at all since the parsing terminated on the exception. Therefore I would suggest that instead of throwing when encountering an unimplemented tag, the library has a special class ASN1UnimplementedTag or something like that that gets added to the output, and then it just continues along with the parsing.

**Comment by wstrange** [comment]
I have not thought about this too much -  but Is it not be better to fail fast with an exception so the error does not propagate?  
 
I am just wondering if returning a not implemented tag would confuse people more.

**Comment by stevenroose** [comment]
I agree with @wstrange. 
Even though there might be cases where not every class in an encoded string might matter, in general, I think providing dummy classes might cause even more problems when people do not expect them.

People don't expect exceptions, but they are made to be unexpected.

**Comment by jonaskello** [comment]
In general I too agree, but I was assuming that all tags would be implemented eventually :-). So what I suggest would be temporary. It would allow for the package to be used in more scenarios in earlier stages, before all tags are implemented. In my case eg. all I wanted to do was extract a public key from a cert, I don't really care about the PrintableStrings. Maybe it could be an opt-in that you manually have to turn on which then is removed when all are implemented.

Anyway, I have implemented what I need so for now I am fine without the ability to parse unimplemented tags :-).

**Comment by wstrange** [comment]
OK - let's close this for now.

If people hit exceptions it will give them good incentive to implement the remaining tags :-)
