### ISSUE TITLE
Use of Int64List

### ISSUE THREAD

**Issue by areiter** [wstrange/asn1lib#18]
Is there a good reason why `ASN1Integer` uses `Int64List` and not always defaults to `BigInteger`?
It seems to be the only thing blocking usage in the browser via dart2js.

**Comment by stevenroose** [comment]
I'm not familiar with the current implementation and don't really have the time to look at it, but if you could reimplement it in a way that works in the browser, I would kindly invite you to! :)

**Comment by pulyaevskiy** [comment]
Hey guys,

If you're still interested would you mind testing #20 on your codebases (if you're using this library)?

**Comment by stevenroose** [comment]
Should be fixed, but additional testing is always a good idea :)

**Comment by stevenroose** [comment]
Solved by #20.
