### ISSUE TITLE
Decoding OIDs from bytes does not complete if OID is not in DN map

### ISSUE THREAD

**Issue by point-source** [wstrange/asn1lib#41]
When decoding an `ASN1ObjectIdentifier` from a byte list, the `fromBytes()` method checks the `DN` map to see if the OID exists and if it does not, the `List<int> oi` and `identifier` string are not populated. The ASN1ObjectIdentifier is still created though but attempting to use it or re-encode it will fail because it's internal variables are null. 

This appears to have been the intended behavior per the code here: https://github.com/wstrange/asn1lib/blob/master/lib/asn1objectidentifier.dart#L122

I would like to remove that DN map check and always create the OID object but before I do that, I wanted to ask what the reasoning is/was behind this current functionality. I don't want to break anything with my changes.

**Comment by wstrange** [comment]
I think @Ephenodrom contributed that code - so I'm not sure what the original intent is.

What you are proposing seems to make sense (if I understand - why not go ahead and create the OID if the bytes decode correctly..)

If you want to create a PR, I'd suggest at least bumping the minor semver, and including a test for it. Worst case we can revert the behaviour. 

WDYT?

**Comment by point-source** [comment]
Sounds good to me. Honestly, I would prefer to remove the DN map altogether. I feel like that is application-specific in what should eventually be a generic asn1 library. That said, I am new to ASN1 and have been researching for the last few weeks so it could be that I don't fully understand what is going on here. Hopefully @Ephenodrom can shed some light on that. In the meantime, I will prepare a PR.

**Comment by Ephenodrom** [comment]
@wstrange / @point-source
Yes it makes only sense to check the DN map when creating the object via the fromBytes to set the readable name. The list of integers should be set in every case.

So there are two ways:
- Create a PR with the fix and a unit test
- Check if the DN map is filled, because it should contain at least the most common ones. Try calling the "registerFrequentNames" method before.

**Comment by point-source** [comment]
I am not actually sure what those names are for. My application is not LDAP. I am using this library for encoding/decoding snmp protocol. Adding enough OIDs to that map to support snmp would be insane. Pretty sure that would result in at least millions of entries. This leads me to believe that the OID decoder should just create an object without a readable name and the implementation of the LDAP library should handle the names in a subclass or something. Still, I don't want to derail your existing project/work so for the moment, I'll just create a PR and test that populates the bytes regardless and only sets the name when it exists in the map. Does that work?

**Comment by wstrange** [comment]
Yea - that sounds reasonable to me.  Set the name if you can, but it should still populate the bytes if no name exits..

**Comment by point-source** [comment]
Hold on, don't merge yet. Might have found another related issue. Still working with it

**Comment by point-source** [comment]
In order to get consistent functionality from the ASN1ObjectIdentifier object, I had to fix the tests first and then fix several methods within the ASN1ObjectIdentifier. 

I believe this should, for the most part, be backward compatible. However, the default ASN1ObjectIdentifier constructor now expects to see its 'oi' argument as a list of components such as `[2.5.4.3]` and decode it to `[0x55, 0x04, 0x03]` (which is correct). The old behavior would have accepted `[85.4.3]` and then decoded it into `[0x55, 0x04, 0x03]` (which, byte-wise, is correct but behavior-wise, is not).

How should I bump the semver seeing as this is technically breaking the backward-compatibility of the default constructor api but is actually fixing it?

**Comment by wstrange** [comment]
This looks good to me.  Let's bump the version to 0.7.0
