### ISSUE TITLE
Inconsistent oi components in asn1objectindentifier when using fromBytes() vs fromComponents()

### ISSUE THREAD

**Issue by point-source** [wstrange/asn1lib#43]
When initializing an `ASN1ObjectIdentifier`, the resulting object holds each id component in a variable called `oi`. Taking the oid string `'1.3.6.1.2.1.1.1'` as an example, you can initialize the object using the fromComponents() method. Alternatively, you can use the equivalent byte list `[0x06, 0x07, 0x2B, 0x06, 0x01, 0x02, 0x01, 0x01, 0x01]` and the fromBytes() method.

I would expect that the resulting object should have identical contents. Unfortunately, the `oi` variable has different contents.

```
var bytes = Uint8List.fromList([0x06, 0x07, 0x2B, 0x06, 0x01, 0x02, 0x01, 0x01, 0x01]);
print(ASN1ObjectIdentifier.fromBytes(bytes).oi);
```
This prints `[1, 3, 6, 1, 2, 1, 1, 1]`, which is correct.

`print(ASN1ObjectIdentifier.fromString('1.3.6.1.2.1.1.1').oi);`

This prints `[43, 6, 1, 2, 1, 1, 1]` which does not appear to be correct as the first two components were not properly split out of their merged encoded byte.

Stranger still, the fromComponent() tests seem to enforce this odd behavior by checking to make sure that the elements aren't fully decoded. Shouldn't a 2-element oid string result in a 2-length oi list?

```
test('fromComponentString', () {
    // ISO member bodies
    {
      var a = ASN1ObjectIdentifier.fromComponentString('1.2');
      expect(a.oi, equals([0x2a]));
    }
    // US (ANSI)
    {
      var a = ASN1ObjectIdentifier.fromComponentString('1.2.840');
      expect(a.oi, equals([0x2a, 0x86, 0x48]));
    }
});


test('fromBytes', () {
    var bytes = Uint8List.fromList([0x06, 0x03, 0x55, 0x04, 0x03]);
    var objId = ASN1ObjectIdentifier.fromBytes(bytes);
    expect(objId.identifier, '2.5.4.3');
    expect(objId.oi.length, 4);
    expect(objId.oi.elementAt(0), 2);
    expect(objId.oi.elementAt(1), 5);
    expect(objId.oi.elementAt(2), 4);
    expect(objId.oi.elementAt(3), 3);
  });
```

**Comment by wstrange** [comment]
@Ephenodrom  Any ideas here?

Is the fromString method possibly not setting the asn.1 length / tag fields correctly?

**Comment by point-source** [comment]
This link explains the encoding/decoding of the first two components pretty well: https://www.sysadmins.lv/blog-en/how-to-encode-object-identifier-to-an-asn1-der-encoded-string.aspx

It seems clear to me that the fromString / fromComponents method just isn't fully encoding/decoding those two first values in the oid. I am happy to fix this and do a pr. Just wanted to make sure I wasn't missing something first.

**Comment by point-source** [comment]
This is fixed in the PR and I have added additional thoughts as a comment on issue #41
