### ISSUE TITLE
Deleted your dev branch!

### ISSUE THREAD

**Issue by kevmoo** [wstrange/asn1lib#50]
I think it has been merged, right?

**Comment by wstrange** [comment]
Hi Kevin - yes - it has been merged.  I'll delete the branch

**Comment by wstrange** [comment]
I merged your PR - I was assuming that would "kick it" - but maybe not?

I'm a GH actions newbie. Is there anything I need to do on my side to enable it?

**Comment by wstrange** [comment]
It looks like the actions did run - but are failing. Will take a look
