### ISSUE TITLE
tag 160 : context specific, but also CONSTRUCTED_BIT

### ISSUE THREAD

**Issue by ysimonx** [wstrange/asn1lib#72]
Hi

The parser returns a ASN1Object with these kinds of bytes

160, 129, 146, 4, 129, 143, 48, 129, 140, 2 ....

The 160 Value contains the Constructed bit and the Context-specific class ...

And it's true that if i remove "160, 129, 146, 4, 129, 143," from the bytes, the remaining Uint8List is parsed as a ASN1Seq ... which is one of the elements that should be returned for the 160 tag ...

while look at the source code the full stream is considered as a generic ASN1Object, 

And it does not consider if the current tag has the Constructed bit before returning a generic ASN1Object 
Is it possible to return elements for this ASN10Object ? ;-)

Sorry if my proposition is weak, I only discovered ASN.1 last week

regards

**Comment by ysimonx** [comment]
[test.tsr.zip](https://github.com/user-attachments/files/16923790/test.tsr.zip)
you'll find here a timestamp response from digicert that contains some of these data

**Comment by wstrange** [comment]
ASN1 is super complex. This is my interpretation of what those bytes mean: 
First byte - is   Context Specific and "Constructed" (bit 6 is on). 
The second byte is the start of the length. It's the indefinite form (bit 8 is 1, value is 1), and there should be one byte following  which is the length of the object. That is 146. 

So the ASN1 object returned should have a length of 146. Is that the case? 

I believe "constructed" means you have to interpret the byte stream you are given based on the documentation provided. It could be some values concatenated together. 

There isn''t really support in the library for context specific objects - but if you know what you are expecting, you should be able to take the bytes (`encodedBytes` or wrap those in a view of the subset you want) - and pass them into a constructor for the type you know.

So if you know its a sequence, you can take those bytes and create a new sequence `ASN1Sequence.fromBytes(my_subset_of bytes)` 

Does that work?

**Comment by ysimonx** [comment]
I will give it a try ;-)
you're right, ASN1 is super complex !
I will give you my answer when I manage to parse my data 

Thank a lot

**Comment by wstrange** [comment]
There is a test `pem_encodec_rsa_keys_test` where it shows the basic idea of how to re-cast an Object to a sequence. Might be helpful?

**Comment by ysimonx** [comment]
> ASN1 is super complex. This is my interpretation of what those bytes mean: First byte - is Context Specific and "Constructed" (bit 6 is on). The second byte is the start of the length. It's the indefinite form (bit 8 is 1, value is 1), and there should be one byte following which is the length of the object. That is 146.
> 
> So the ASN1 object returned should have a length of 146. Is that the case?
> 
> I believe "constructed" means you have to interpret the byte stream you are given based on the documentation provided. It could be some values concatenated together.
> 
> There isn''t really support in the library for context specific objects - but if you know what you are expecting, you should be able to take the bytes (`encodedBytes` or wrap those in a view of the subset you want) - and pass them into a constructor for the type you know.
> 
> So if you know its a sequence, you can take those bytes and create a new sequence `ASN1Sequence.fromBytes(my_subset_of bytes)`
> 
> Does that work?

yes, it is working with a sublist of the bytes ;-)
ty
