### ISSUE TITLE
encodedBytes cache not updated when object modified

### ISSUE THREAD

**Issue by RemarkIt** [wstrange/asn1lib#73]
Hi, below i describe my problem on an example. The issue has given me some hard time  and i am not aware of any workaround I would be happy with. 

1.  var attrList = ASN1Sequence();
2. attrList.add(someObject)
3. attrList.encodedBytes  //here the bytes are cached into _encodedBytes
4. attrList.add(someAnotherObject)
5.  attrList.encodedBytes // outputs old value

i guess the cache should be cleared when the object is updated? e.g. extending the add method to 

  void add(ASN1Object o) {
    elements.add(o);
   _encodedBytes = null;
  }

**Comment by wstrange** [comment]
It's an unusual access pattern, but yea, that's a bug. 

I'll see if I can push a fix.

**Comment by RemarkIt** [comment]
Thank you, that was fast! It is just a bit unfortunate that starting the previous version, asn1lib depends on collection 1.19.0 which is incompatible with flutter sdk on stable channel (pinned to 1.18). I see that master channel us already updated, so lets hope stable follows soon :).

I could verify that all my use cases are resolved. Although let me mention that similar issues might arise e.g. on ASN1Set, which also provides Add method. Sorry, i think i should have mentioned in the description.

Nevertheless, thanks again. Great package

**Comment by wstrange** [comment]
Ahh, I didn't realize the collection dependency was a problem. It's only needed for a single equals method. I'm pretty sure I can factor it out, or at least just use it as a test only dependency.

**Comment by wstrange** [comment]
I just pushed 1.5.8.  The collection dependency is only for testing, and is 1.18. 

LM if that fixes your problem.
